import { SocialMediaSidebarComponent } from "@/components/social-media-sidebar";
import React from "react";

const UserNotifications = () => {
  const notifications = {
    notification1: {
      id: "n1",
      title: "New Message",
      message: "You have received a new message from Sarah",
      type: "message",
      timestamp: "2024-01-01T10:00:00Z",
      isRead: false,
      priority: "medium",
    },
    notification2: {
      id: "n2",
      title: "Payment Received",
      message: "Payment of $50.00 has been processed",
      type: "payment",
      timestamp: "2024-01-01T10:15:00Z",
      isRead: true,
      priority: "high",
    },
    notification3: {
      id: "n3",
      title: "System Update",
      message: "New version 2.0 is available for download",
      type: "system",
      timestamp: "2024-01-01T10:30:00Z",
      isRead: false,
      priority: "low",
    },
    notification4: {
      id: "n4",
      title: "Calendar Event",
      message: "Team meeting in 30 minutes",
      type: "calendar",
      timestamp: "2024-01-01T11:00:00Z",
      isRead: false,
      priority: "high",
    },
    notification5: {
      id: "n5",
      title: "Friend Request",
      message: "John Smith wants to connect",
      type: "social",
      timestamp: "2024-01-01T11:15:00Z",
      isRead: false,
      priority: "low",
    },
    notification6: {
      id: "n6",
      title: "Order Shipped",
      message: "Your order #12345 has been shipped",
      type: "order",
      timestamp: "2024-01-01T11:30:00Z",
      isRead: true,
      priority: "medium",
    },
    notification7: {
      id: "n7",
      title: "Security Alert",
      message: "New login detected from unknown device",
      type: "security",
      timestamp: "2024-01-01T11:45:00Z",
      isRead: false,
      priority: "high",
    },
    notification8: {
      id: "n8",
      title: "Subscription Renewal",
      message: "Your subscription will renew in 3 days",
      type: "billing",
      timestamp: "2024-01-01T12:00:00Z",
      isRead: false,
      priority: "medium",
    },
    notification9: {
      id: "n9",
      title: "New Comment",
      message: "Lisa commented on your post",
      type: "social",
      timestamp: "2024-01-01T12:15:00Z",
      isRead: true,
      priority: "low",
    },
    notification10: {
      id: "n10",
      title: "Storage Full",
      message: "Your cloud storage is 90% full",
      type: "system",
      timestamp: "2024-01-01T12:30:00Z",
      isRead: false,
      priority: "high",
    },
    notification11: {
      id: "n11",
      title: "Task Completed",
      message: "Project milestone achieved",
      type: "task",
      timestamp: "2024-01-01T12:45:00Z",
      isRead: true,
      priority: "medium",
    },

    notification12: {
      id: "n12",
      title: "Weather Alert",
      message: "Heavy rain expected tomorrow",
      type: "weather",
      timestamp: "2024-01-01T13:00:00Z",
      isRead: false,
      priority: "medium",
    },
    notification13: {
      id: "n13",
      title: "Password Changed",
      message: "Your account password was updated",
      type: "security",
      timestamp: "2024-01-01T13:15:00Z",
      isRead: true,
      priority: "high",
    },
    notification14: {
      id: "n14",
      title: "New Follower",
      message: "Alex started following you",
      type: "social",
      timestamp: "2024-01-01T13:30:00Z",
      isRead: false,
      priority: "low",
    },
    notification15: {
      id: "n15",
      title: "Maintenance Notice",
      message: "System maintenance scheduled for tonight",
      type: "system",
      timestamp: "2024-01-01T13:45:00Z",
      isRead: false,
      priority: "medium",
    },
    notification16: {
      id: "n16",
      title: "Document Shared",
      message: "Mike shared a document with you",
      type: "document",
      timestamp: "2024-01-01T14:00:00Z",
      isRead: false,
      priority: "medium",
    },
    notification17: {
      id: "n17",
      title: "Reminder",
      message: "Doctor's appointment tomorrow",
      type: "calendar",
      timestamp: "2024-01-01T14:15:00Z",
      isRead: false,
      priority: "high",
    },
    notification18: {
      id: "n18",
      title: "Low Battery",
      message: "Device battery at 10%",
      type: "system",
      timestamp: "2024-01-01T14:30:00Z",
      isRead: false,
      priority: "high",
    },
    notification19: {
      id: "n19",
      title: "New Review",
      message: "Your product received a 5-star review",
      type: "review",
      timestamp: "2024-01-01T14:45:00Z",
      isRead: true,
      priority: "low",
    },
    notification20: {
      id: "n20",
      title: "File Upload Complete",
      message: "Your file has been uploaded successfully",
      type: "system",
      timestamp: "2024-01-01T15:00:00Z",
      isRead: true,
      priority: "low",
    },
    notification21: {
      id: "n21",
      title: "Account Verification",
      message: "Please verify your email address",
      type: "account",
      timestamp: "2024-01-01T15:15:00Z",
      isRead: false,
      priority: "high",
    },
    notification22: {
      id: "n22",
      title: "New Feature",
      message: "Check out our latest app features",
      type: "update",
      timestamp: "2024-01-01T15:30:00Z",
      isRead: false,
      priority: "medium",
    },
    notification23: {
      id: "n23",
      title: "Payment Due",
      message: "Invoice #789 is due tomorrow",
      type: "billing",
      timestamp: "2024-01-01T15:45:00Z",
      isRead: false,
      priority: "high",
    },
    notification24: {
      id: "n24",
      title: "Birthday Reminder",
      message: "Emma's birthday is tomorrow",
      type: "reminder",
      timestamp: "2024-01-01T16:00:00Z",
      isRead: false,
      priority: "medium",
    },
    notification25: {
      id: "n25",
      title: "Network Issue",
      message: "Weak internet connection detected",
      type: "system",
      timestamp: "2024-01-01T16:15:00Z",
      isRead: false,
      priority: "medium",
    },
    notification26: {
      id: "n26",
      title: "Achievement Unlocked",
      message: "You've reached level 10!",
      type: "achievement",
      timestamp: "2024-01-01T16:30:00Z",
      isRead: true,
      priority: "low",
    },
    notification27: {
      id: "n27",
      title: "Travel Update",
      message: "Flight DL123 delayed by 1 hour",
      type: "travel",
      timestamp: "2024-01-01T16:45:00Z",
      isRead: false,
      priority: "high",
    },
    notification28: {
      id: "n28",
      title: "Package Delivery",
      message: "Your package will arrive today",
      type: "delivery",
      timestamp: "2024-01-01T17:00:00Z",
      isRead: false,
      priority: "medium",
    },
    notification29: {
      id: "n29",
      title: "Account Activity",
      message: "Unusual login attempt detected",
      type: "security",
      timestamp: "2024-01-01T17:15:00Z",
      isRead: false,
      priority: "high",
    },
    notification30: {
      id: "n30",
      title: "Subscription Expired",
      message: "Please renew your subscription",
      type: "billing",
      timestamp: "2024-01-01T17:30:00Z",
      isRead: false,
      priority: "high",
    },
    notification31: {
      id: "n31",
      title: "Group Invitation",
      message: "You're invited to join Project X",
      type: "social",
      timestamp: "2024-01-01T17:45:00Z",
      isRead: false,
      priority: "medium",
    },
    notification32: {
      id: "n32",
      title: "Battery Charged",
      message: "Device is fully charged",
      type: "system",
      timestamp: "2024-01-01T18:00:00Z",
      isRead: true,
      priority: "low",
    },
    notification33: {
      id: "n33",
      title: "New Job Opening",
      message: "Senior Developer position available",
      type: "job",
      timestamp: "2024-01-01T18:15:00Z",
      isRead: false,
      priority: "medium",
    },
    notification34: {
      id: "n34",
      title: "Data Backup",
      message: "Weekly backup completed",
      type: "system",
      timestamp: "2024-01-01T18:30:00Z",
      isRead: true,
      priority: "low",
    },
    notification35: {
      id: "n35",
      title: "Price Drop",
      message: "Item in your wishlist is on sale",
      type: "shopping",
      timestamp: "2024-01-01T18:45:00Z",
      isRead: false,
      priority: "medium",
    },
    notification36: {
      id: "n36",
      title: "New Article",
      message: "Latest tech news published",
      type: "news",
      timestamp: "2024-01-01T19:00:00Z",
      isRead: false,
      priority: "low",
    },
    notification37: {
      id: "n37",
      title: "Server Status",
      message: "Server maintenance completed",
      type: "system",
      timestamp: "2024-01-01T19:15:00Z",
      isRead: true,
      priority: "medium",
    },
    notification38: {
      id: "n38",
      title: "Video Call",
      message: "Missed video call from Tom",
      type: "call",
      timestamp: "2024-01-01T19:30:00Z",
      isRead: false,
      priority: "high",
    },
    notification39: {
      id: "n39",
      title: "Location Alert",
      message: "You're near a favorite restaurant",
      type: "location",
      timestamp: "2024-01-01T19:45:00Z",
      isRead: false,
      priority: "low",
    },
    notification40: {
      id: "n40",
      title: "Database Update",
      message: "Database successfully migrated",
      type: "system",
      timestamp: "2024-01-01T20:00:00Z",
      isRead: true,
      priority: "high",
    },
    notification41: {
      id: "n41",
      title: "New Poll",
      message: "Vote on team lunch options",
      type: "poll",
      timestamp: "2024-01-01T20:15:00Z",
      isRead: false,
      priority: "low",
    },
    notification42: {
      id: "n42",
      title: "Antivirus Alert",
      message: "Virus scan completed",
      type: "security",
      timestamp: "2024-01-01T20:30:00Z",
      isRead: true,
      priority: "medium",
    },
    notification43: {
      id: "n43",
      title: "Milestone Reached",
      message: "1000 followers achieved",
      type: "achievement",
      timestamp: "2024-01-01T20:45:00Z",
      isRead: false,
      priority: "low",
    },
    notification44: {
      id: "n44",
      title: "Traffic Alert",
      message: "Heavy traffic on usual route",
      type: "traffic",
      timestamp: "2024-01-01T21:00:00Z",
      isRead: false,
      priority: "high",
    },
    notification45: {
      id: "n45",
      title: "Profile Update",
      message: "Profile picture changed",
      type: "account",
      timestamp: "2024-01-01T21:15:00Z",
      isRead: true,
      priority: "low",
    },
    notification46: {
      id: "n46",
      title: "Data Usage",
      message: "80% of data plan used",
      type: "system",
      timestamp: "2024-01-01T21:30:00Z",
      isRead: false,
      priority: "medium",
    },
    notification47: {
      id: "n47",
      title: "Emergency Alert",
      message: "Severe weather warning in your area",
      type: "emergency",
      timestamp: "2024-01-01T21:45:00Z",
      isRead: false,
      priority: "high",
    },
    notification48: {
      id: "n48",
      title: "Warranty Expiring",
      message: "Device warranty expires next week",
      type: "product",
      timestamp: "2024-01-01T22:00:00Z",
      isRead: false,
      priority: "medium",
    },
    notification49: {
      id: "n49",
      title: "New Update",
      message: "Software update available",
      type: "system",
      timestamp: "2024-01-01T22:15:00Z",
      isRead: false,
      priority: "medium",
    },
    notification50: {
      id: "n50",
      title: "Goal Achieved",
      message: "Daily step goal completed",
      type: "health",
      timestamp: "2024-01-01T22:30:00Z",
      isRead: true,
      priority: "low",
    },
  };
  return (
    <div className="flex gap-2">
      {/* <SocialMediaSidebarComponent /> */}

      <div className=" p-4 bg-green-100">
        <div className="text-2xl font-bold">User Notifications</div>
        <div className="flex flex-col">
          {Object.values(notifications).map((val, key) => {
            return (
              <div
                key={key}
                className="flex gap-4 justify-between hover:bg-blue-200 p-2 text-sm"
              >
                <div>{val.message}</div>
                <div>{val.timestamp}</div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default UserNotifications;
